### PR TITLE
Add Positioning system mode indicator to GPRMC

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by dassencio** [comment]
@Florin9doi: This looks like a very interesting addition, but it does not appear on the [definition of GPRMC](http://aprs.gids.nl/nmea/#rmc) sentences which was originally used when I built this application.

It seems that this is only valid for [NMEA 2.3 and later](https://gpsd.gitlab.io/gpsd/NMEA.html#_rmc_recommended_minimum_navigation_information). I'm somewhat concerned about this because it will likely break lots of applications which depend on the structure of RMC sentences without the "FAA mode indicator".

**Comment by dassencio** [comment]
@Florin9doi: This looks like a very interesting addition, but it does not appear in the definition of [GPRMC sentences](http://aprs.gids.nl/nmea/#rmc) sentences which was originally used when I built this application.

It seems that this is only valid for [NMEA 2.3 and later](https://gpsd.gitlab.io/gpsd/NMEA.html#_rmc_recommended_minimum_navigation_information). I'm somewhat concerned about this because it will likely break lots of applications which depend on the structure of RMC sentences without the "FAA mode indicator".

**Comment by dassencio** [comment]
@Florin9doi: This looks like a very interesting addition, but it does not appear in the definition of [GPRMC sentences](http://aprs.gids.nl/nmea/#rmc) which was originally used when I built this application.

It seems that this is only valid for [NMEA 2.3 and later](https://gpsd.gitlab.io/gpsd/NMEA.html#_rmc_recommended_minimum_navigation_information). I'm somewhat concerned about this because it will likely break lots of applications which depend on the structure of RMC sentences without the "FAA mode indicator".

**Comment by Florin9doi** [comment]
ok

**Pull request closed without merging**
